# Generated by Django 6.0 on 2025-12-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_description_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='winning_prize',
            field=models.CharField(default='TBA', max_length=100),
        ),
    ]
